export const POST_MAIN_DATA = 'POST_MAIN_DATA'
export const POST_MAIN_DATA_REQUEST = 'POST_MAIN_DATA_REQUEST'
export const POST_MAIN_DATA_SUCCESS = 'POST_MAIN_DATA_SUCCESS'
export const POST_MAIN_DATA_FAILURE = 'POST_MAIN_DATA_FAILURE'

