export const ADD_CART_DATA = "ADD_CART_DATA";
export const ADD_CART_DATA_REQUEST = "ADD_CART_DATA_REQUEST";
export const ADD_CART_DATA_SUCCESS = "ADD_CART_DATA_SUCCESS";
export const ADD_CART_DATA_FAILURE = "ADD_CART_DATA_FAILURE";

